server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://root:gYuMCAyeToCxfNZMhqJbFtFDbRvPNXJm@interchange.proxy.rlwy.net:21793/railway
    username: root
    password: gYuMCAyeToCxfNZMhqJbFtFDbRvPNXJm
    # url: "jdbc:mysql://localhost:3306/flight_ticket"
    # username: root
    # password:
#  logging:
#    level:
#      org:
#        springframework:
#          security: DEBUG
