server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://root:IRmjeoYoKodOIhCgfoBZevyMwCsHzXhr@trolley.proxy.rlwy.net:36393/railway
    username: root
    password: IRmjeoYoKodOIhCgfoBZevyMwCsHzXhr
    # url: "jdbc:mysql://localhost:3306/flight_ticket"
    # username: root
    # password:
#  logging:
#    level:
#      org:
#        springframework:
#          security: DEBUG
